### ISSUE TITLE
Question - caching entire repos 

### ISSUE THREAD

**Issue by Bonn93** [zerolagtime/Powershell#5]
Can you provide an example on mirroring say the entire CentOS7 repo but exclude .ISOs? 

It requires the -Repository flag be set, what would be used for all folders under http://centos.mirror.digitalpacific.com.au/7/ ?

**Comment by zerolagtime** [comment]
Syncing an entire repository would require a functioning Linux system and you would use rsync (e.g. `rsync  -avSHP --delete --exclude "local*" --exclude "isos" --exclude "*debuginfo*" --bwlimit=900k  $uri $destfolder`).  This tool is designed to mirror a single yum repository, examples are: os, updates, extras, and cloud.  Each of them has their own "repodata" folder and you need one preferences file per yum repo.  Consider that a single file in /etc/yum/repos.d (or is it /etc/yum.repos.d?) contains details on numerous repositories.  Each of those entries gets a different preferences file.
For politeness, I would be cautious about when you sync an entire repo.  The mirroring host may not look kindly upon it, so spread it out over a few days.  Consider adding a `Start-Sleep -Seconds 2` between file pulls.

**Comment by Bonn93** [comment]
Thanks for all the detail! Lots to go off, cheers.
